nanoreview-django/processorsrankingpage/mobile_processors/urls.py
from django.urls import path, include

from . import views
app_name="mobile_processors"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:processor_id>/', views.detail, name="detail"),
    path('load_processors', views.load_processors, name='load_processors')
]

nanoreview-django/processorsrankingpage/processorsrankingpage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mobile_processors/',include("mobile_processors.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
]

nanoreview-django/processorsrankingpage/mobile_processors/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
from django.db import models


# Create your models here.
class MobileProcessor(models.Model):
    class Category(models.TextChoices):
        FLAGSHIP = "Flagship", _("Flagship")
        MID_RANGE = "Mid range", _("Mid range")
        LOW_END = "Low end", _("Low end")

    model = models.CharField(max_length=100, unique=True)
    manufacturer = models.CharField(max_length=30)
    nano_review_score = models.IntegerField()
    nano_review_label = models.CharField(max_length=10)
    antutu_score = models.IntegerField()
    clock = models.IntegerField(null=True)
    cores_summary=models.CharField(max_length=20, null=True)
    geek_bench_score_single = models.IntegerField(null=True)
    geek_bench_score_multi = models.IntegerField(null=True)
    geek_bench_score_gpu = models.IntegerField(null=True)
    score_3d_mark = models.IntegerField(null=True)
    fps_3d_mark = models.IntegerField(null=True)
    cpu_frequency = models.IntegerField(null=True)
    architecture = models.CharField(max_length=200, null=True)
    cores = models.IntegerField(null=True)
    l2_cache = models.CharField(max_length=30, null=True)
    l3_cache = models.CharField(max_length=30, null=True)
    process_nanometers = models.IntegerField(null=True)
    tdp_watt = models.IntegerField(null=True)
    gpu_name = models.CharField(max_length=200, null=True)
    gpu_frequency = models.IntegerField(null=True)
    gpu_flops_gigaflops = models.IntegerField(null=True)
    gpu_pipelines = models.IntegerField(null=True)
    memory_type = models.CharField(max_length=20, null=True)
    memory_frequency = models.IntegerField(null=True)
    memory_max_size = models.IntegerField(null=True)
    max_display_resolution = models.CharField(max_length=60, null=True)
    max_camera_resolution = models.CharField(max_length=60, null=True)
    video_capture = models.CharField(max_length=60, null=True)
    video_playbacks = models.CharField(max_length=60, null=True)
    support_4g = models.CharField(max_length=30, null=True)
    support_5g = models.BooleanField(null=True)
    download_max_speed = models.IntegerField(null=True)
    upload_max_speed = models.IntegerField(null=True)
    wifi_version = models.IntegerField(null=True)
    bluetooth_version = models.DecimalField(decimal_places=1, max_digits=4, null=True)
    announced = models.DateField(null=True)
    category = models.CharField(choices=Category.choices, max_length=20,null=True)
    source = models.CharField(null=True, max_length=255)

nanoreview-django/processorsrankingpage/mobile_processors/views.py
from time import sleep

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django_tables2 import SingleTableView
from . import ProcessorFilter
from .ProcessorFilter import MobileProcessorFilter
from .models import MobileProcessor
from .table import MobileProcessorTable
from mobile_processors.bridge.get_processors_from_nanoreview import start_crawler
from django_tables2 import RequestConfig
from django.urls import reverse


# Create your views here.
def index(request):
    mobile_processors_list = MobileProcessor.objects.all()
    f = MobileProcessorFilter(request.GET, queryset=mobile_processors_list)
    table = MobileProcessorTable(f.qs)
    #table.paginate(page=request.GET.get("page", 1), per_page=10)
    RequestConfig(request, paginate={"page": request.GET.get("page", 1), "per_page": 10}).configure(table)
    context = {
        "table": table,
        'filter': f,
#        'redirect_to': request.path
    }
    return render(request, "mobile_processors/index.html", context)


def detail(request, processor_id):
    processor = get_object_or_404(MobileProcessor, pk=processor_id)
    return render(request, "mobile_processors/detail.html", {"processor": processor})


def load_processors(request):
    if request.method == "POST":
        start_crawler()
        # sleep(10)
    return HttpResponse("OK", status=200)

nanoreview-django/processorsrankingpage/mobile_processors/templates/mobile_processors/detail.html
<!DOCTYPE html>
{% load i18n %}
{% load custom_filters %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans "Details of processor" %} {{processor.manufacturer}} {{processor.model}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <style type="text/css">
        section{
            margin-top: 1rem;
        }
    </style>
</head>
<body>
<div class="container">
    <h1 id="processor_name_model" class="text-center">
        {{processor.manufacturer}} {{processor.model}}
    </h1>
    <section id="main_information">
        <div class="row">
            <div class="col-sm-4"><strong>GPU</strong></div>
            <div class="col-sm-8">{{processor.gpu_name}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Cores" %}</strong></div>
            <div class="col-sm-8">{{processor.cores}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>Clock</strong></div>
            <div class="col-sm-8">{{processor.clock}} Mhz</div>
        </div>
    </section>
    <section id="section_benchmark">
        <h2 class="bg-light bg-gradient">{% trans "Scores (Nanoreview, Antutu, Geekbench and 3D-Mark)" %}</h2>
        <div class="row">
            <div class="col-sm-4"><strong>Nanoreview</strong></div>
            <div class="col-sm-8">{{processor.nano_review_score}} [{{processor.nano_review_label}}]</div>
        </div>
        <div class="row progress mx-0 mb-1" style="height:0.15rem">
             <div class="progress-bar" id="nanoreview-score" style=" width:{{processor.nano_review_score}}%">
              </div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>Antutu</strong></div>
            <div class="col-sm-8">{{processor.antutu_score}}</div>
        </div>
        {% if processor.geek_bench_score_single %}
        <div class="row">
            <div class="col-sm-4"><strong>GeekBench (single-core)</strong></div>
            <div class="col-sm-8">{{processor.geek_bench_score_single}}</div>
        </div>
        {% endif %}
        {% if processor.geek_bench_score_multi %}
        <div class="row">
            <div class="col-sm-4"><strong>GeekBench (multi-core)</strong></div>
            <div class="col-sm-8">{{processor.geek_bench_score_multi}}</div>
        </div>
        {% endif %}
        {% if processor.geek_bench_score_gpu %}
        <div class="row">
            <div class="col-sm-4"><strong>GeekBench (GPU)</strong></div>
            <div class="col-sm-8">{{processor.geek_bench_score_gpu}}</div>
        </div>
        {% endif %}
        {% if processor.score_3d_mark %}
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "3D-Mark score" %}</strong></div>
            <div class="col-sm-8">{{processor.score_3d_mark}}</div>
        </div>
        {% endif %}
        {% if processor.fps_3d_mark %}
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "3D-Mark graphics test" %}</strong></div>
            <div class="col-sm-8">{{processor.fps_3d_mark}} FPS</div>
        </div>
        {% endif %}
    </section>
    <section id="section_cpu">
        <h2 class="bg-light bg-gradient">CPU</h2>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans Architecture %}</strong></div>
            <div class="col-sm-8">{{processor.architecture|comma_to_br}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans Cores %}</strong></div>
            <div class="col-sm-8">{{processor.cores}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans Frequency %}</strong></div>
            <div class="col-sm-8">{{processor.clock}} MHz</div>
        </div>
        {% if processor.l2_cache %}
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "L2 Cache" %} </strong></div>
            <div class="col-sm-8">{{processor.l2_cache}}</div>
        </div>
        {% endif %}
        {% if processor.l3_cache %}
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "L3 Cache" %}</strong></div>
            <div class="col-sm-8">{{processor.l3_cache}}</div>
        </div>
        {% endif %}
        {% if processor.process_nanometers %}
        <div class="row">
            <div class="col-sm-4"><strong>{% trans Process %}</strong></div>
            <div class="col-sm-8">{{processor.process_nanometers}} {% trans nanometers}</div>
        </div>
        {% endif %}
        {% if processor.tdp_watt %}
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "TDP (Sustained Power Limit)" %}</strong></div>
            <div class="col-sm-8">{{processor.tdp_watt}} W</div>
        </div>
        {% endif %}
    </section>
    <section id="section_gpu">
        <h2 class="bg-light bg-gradient"></h2>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "GPU Name" %}</strong></div>
            <div class="col-sm-8">{{processor.gpu_name}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "GPU Frequency" %}</strong></div>
            <div class="col-sm-8">{{processor.gpu_frequency}} MHz</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>Pipelines</strong></div>
            <div class="col-sm-8">{{processor.gpu_pipelines}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>Flops</strong></div>
            <div class="col-sm-8">{{processor.gpu_flops_gigaflops}} Gigaflops</div>
        </div>
    </section>
    <section id="section_memory">
        <h2 class="bg-light bg-gradient">{% trans Memory %}</h2>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Memory type"%}</strong></div>
            <div class="col-sm-8">{{processor.memory_type}} MHz</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Memory frequency" %}</strong></div>
            <div class="col-sm-8">{{processor.memory_frequency}} Mhz</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Max size" %}</strong></div>
            <div class="col-sm-8">{{processor.memory_max_size}} GB</div>
        </div>
    </section>
    <section id="section_multimedia">
        <h2 class="bg-light bg-gradient">{% trans Multimedia %}</h2>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Max display resolution"%}</strong></div>
            <div class="col-sm-8">{{processor.max_display_resolution}} MHz</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Max camera resolution"%}</strong></div>
            <div class="col-sm-8">{{processor.max_camera_resolution}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Video Capture" %}</strong></div>
            <div class="col-sm-8">{{processor.video_capture}} Gigaflops</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Video Playback" %}</strong></div>
            <div class="col-sm-8">{{processor.video_playbacks}} Gigaflops</div>
        </div>
    </section>
    <section id="section_connectivity">
        <h2 class="bg-light bg-gradient">{% trans "Connectivity" %}</h2>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "4G support" %}</strong></div>
            <div class="col-sm-8">{{processor.support_4g}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "5G support" %}</strong></div>
            <div class="col-sm-8">{{processor.support_5g|yesno }}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "download max speed" %}</strong></div>
            <div class="col-sm-8">{{processor.download_max_speed}} Mbps</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Upload max speed" %}</strong></div>
            <div class="col-sm-8">{{processor.upload_max_speed}} Mbps</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Wi-fi version" %}</strong></div>
            <div class="col-sm-8">{{processor.wifi_version}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Bluetooth version" %}</strong></div>
            <div class="col-sm-8">{{processor.bluetooth_version}}</div>
        </div>
    </section>
    <section id="section_info">
        <h2 class="bg-light bg-gradient"></h2>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Announced" %}</strong></div>
            <div class="col-sm-8">{{processor.announced |date:"m/Y"}}</div>
        </div>
        <div class="row">
            <div class="col-sm-4"><strong>{% trans "Category" %}</strong></div>
            <div class="col-sm-8">{{processor.get_category_display}}</div>
        </div>
    </section>
    <section id="buttons" class="d-flex justify-content-center my-1">
        <button  id="btnVoltar" type="button" class="btn btn-primary">{% trans "Back" %}</button>
    </section>
    <footer>
                {% trans "Source" %}: <a href="{{processor.source}}" target="_blank">Nanoreview</a>
       </footer>
</div>
</body>
    <script language="JavaScript">
        btnVoltar = document.getElementById("btnVoltar")
        btnVoltar.onclick = voltar

        function voltar(){
            location.href="{% url 'mobile_processors:index' %}"
        }
    </script>
</html>

nanoreview-django/processorsrankingpage/mobile_processors/templates/mobile_processors/index.html
<!DOCTYPE html>
{% load i18n %}
{% load render_table from django_tables2 %}
{%load crispy_forms_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans "Mobile processors" %}</title>
    <!-- font-awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <style type="text/css">
        .form-label{
            font-size: 1.2em
        }
        .btn i.fa:before {
            content: "\f139";
        }

        .btn.collapsed i.fa:before {
            content: "\f13a";
        }

        #btnLoadProcessors{
            display: block;
        }

    </style>
</head>
<body>
   <div class="container-fluid pt-4">
        <h1 class="h2 text-center mb-3">{% trans "Mobile processors list obtained from NanoReview web-site" %}</h1>
		<div class="mb-4">
            <form name="formLanguage" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <input id="language" name="language" type="hidden">
            </form>
            <a href="#" class="me-2" onclick="set_language('en')"> <img src="https://flagsapi.com/US/flat/32.png" alt="English version" /></a>
            <a href="#" class="me-2" onclick="set_language('pt-BR')"> <img src="https://flagsapi.com/BR/flat/32.png" alt="Versão em português" /></a>
            <a href="#" class="me-2" onclick="set_language('es')"> <img src="https://flagsapi.com/ES/flat/32.png" alt="Versión en español" /></a>
		</div>
        <div id="accordion" class="mb-4">
            <div class="card">
                <div class="card-header">
                    <button class="btn" data-bs-toggle="collapse" data-bs-target="#collapseOne">
                        <i class="fa" aria-hidden="true"></i>
                        {% trans "Define Filters" %}
                    </button>
                </div>
                <div id="collapseOne" class="collapse show" data-bs-parent="#accordion">
                    <div class="card-body">
                        <form method="get">
                            {{  filter.form|crispy }}
                            <div class="d-flex justify-content-center">
                                <input type="submit" class="btn btn-primary mx-1" value='{% trans "Filter" %}'/>
                                <a class="btn btn-primary mx-1" href="{%  url 'mobile_processors:index' %}">{% trans "Clean" %}</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% if table %}
 {% render_table table %}
{% else %}
    <p> {% trans "There is no processors on the records" %}</p>
{% endif %}
        <button  id="btnLoadProcessors" type="button" class=" btn btn-primary my-3 mx-auto">{% trans "Load processors list" %}</button>
       <footer>
                {% trans "Source" %}: <a href="https://nanoreview.net/en/soc-list/rating" target="_blank">Nanoreview</a>
       </footer>
   </div>

<!-- modal que exibe status de carregando -->

<!-- The Modal -->
<div class="modal" id="modalLoadingProcessors" data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">{% trans "Wait" %}</h4>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div class="text-center">
            <div class="spinner-border"></div><br>
             <span  role="status" aria-hidden="true">{% trans "Loading Processors List" %}</span>
          </div>
      </div>


    </div>
  </div>
</div>

</body>
    <script language="JavaScript">
        const csrftoken = Cookies.get('csrftoken');
        btnLoadProcessors = document.getElementById("btnLoadProcessors")
        btnLoadProcessors.onclick = load_processors


        function load_processors(){
            procModal = new bootstrap.Modal(document.getElementById('modalLoadingProcessors'));
            procModal.show();
	        var r = new XMLHttpRequest();
            r.open("POST", "{% url 'mobile_processors:load_processors' %}", true);
            r.setRequestHeader('X-CSRFToken', csrftoken)
            r.onreadystatechange = function () {
                if (r.readyState != 4 || r.status != 200){
                    procModal.hide()
                    return;
                }
                alert('{% trans "Processor list imported successfully" %}' );
                location.reload()
            };
            r.send()
        }
        function set_language(idLang){
            document.getElementById('language').value=idLang;
            document.forms['formLanguage'].submit();
        }
    </script>

</html>

nanoreview-django/processorsrankingpage/mobile_processors/templates/my_range_widget.html
<div class="d-flex">
    {% for widget in widget.subwidgets %}
    <div class="flex-grow-1">
        {% include widget.template_name %}
    </div>
    {% if forloop.first %}
    <span class="align-text-bottom">_</span>
    {% endif %}
    {% endfor %}
</div>